- name: enable and start wazuh agent
  listen: "start/enable wazuh-agent"
  ansible.builtin.service:
    enabled: true
    name: "wazuh-agent"
    state: "started"

- name: start wazuh if service failed
  listen: "start wazuh agent"
  ansible.builtin.shell: "/var/ossec/bin/wazuh-control start"
