---

- name: "packages: Debug"
  ansible.builtin.debug:
    var: pf_packages_install
  when: pf_debug|bool

- name: "packages: Install packages"
  community.general.pkgng:
    name: "{{ item }}"
  loop: "{{ pf_packages_install }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method|lower == 'packages'

- name: "packages: Install ports"
  community.general.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ pf_packages_install }}"
  register: result
  until: result is succeeded
  retries: "{{ freebsd_install_retries }}"
  delay: "{{ freebsd_install_delay }}"
  when: freebsd_install_method|lower == 'ports'

# EOF
...
