---

- name: "pfconf: Debug"
  vars:
    msg: |-
         pf_type: {{ pf_type }}
         pf_ext_if: {{ pf_ext_if }}
         pf_conf_template: {{ pf_conf_template }}
         pf_conf_only: {{ pf_conf_only }}
         pf_conf_validate: {{ pf_conf_validate }}
         pf_conf_validate_command: {{ pf_conf_validate_command }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"
  when: pf_debug|bool

- name: "pfconf: Configure and validate"
  block:

    - name: "pfconf: Configure rules using template {{ pf_conf_template }} and validate"
      ansible.builtin.template:
        dest: /etc/pf.conf
        src: "{{ pf_conf_template }}"
        owner: root
        group: wheel
        mode: '0640'
        backup: "{{ pf_backup_conf }}"
        validate: "{{ pf_conf_validate_command }}"
      notify: reload pf

  rescue:
    - name: "pfconf: Validation failed"
      ansible.builtin.fail:
        msg: "[ERR] Validation error: {{ ansible_failed_result }}"

  when: pf_conf_validate|bool

- name: "pfconf: Configure and do not validate"
  block:

    - name: "pfconf: Fail when pf_conf_validate=False and pf_conf_only=False"
      ansible.builtin.fail:
        msg: "[ERR] Validation can be turned off if pf_conf_only=True."
      when: not pf_conf_only|bool

    - name: "pfconf: Configure rules using template {{ pf_conf_template }} and do not validate"
      ansible.builtin.template:
        dest: /etc/pf.conf
        src: "{{ pf_conf_template }}"
        owner: root
        group: wheel
        mode: '0640'
        backup: "{{ pf_backup_conf }}"

  when: not pf_conf_validate|bool

# EOF
...
