- name: Import gpg key
  ansible.builtin.rpm_key:
    key: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
    state: present

- name: Add repository
  ansible.builtin.blockinfile:
    path: "/etc/yum.repos.d/wazuh.repo"
    create: true
    block: |
      [wazuh]
      gpgcheck=1
      gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
      enabled=1
      name=EL-$releasever - Wazuh
      baseurl=https://packages.wazuh.com/4.x/yum/
      protect=1

- name: install client
  ansible.builtin.yum:
    name: wazuh-agent
    state: present

- name: Add manager IP
  ansible.builtin.replace:
    path: "/var/ossec/etc/ossec.conf"
    regexp: "MANAGER_IP"
    replace: "{{ manager_ip }}"

- name: Add hostname
  ansible.builtin.replace:
    path: "/var/ossec/etc/ossec.conf"
    regexp: "</server>"
    replace: "</server>\n    <enrollment>\n      <agent_name>{{ inventory_hostname }}</agent_name>\n    </enrollment>"

- name: Check ossec.conf for audit.log
  ansible.builtin.command: grep -Fq 'audit.log' /var/ossec/etc/ossec.conf
  register: grep_ossec_conf
  failed_when: false
  changed_when: false

- name: Edit ossec conf file with audit
  ansible.builtin.blockinfile:
    path: "/var/ossec/etc/ossec.conf"
    block: |
      <ossec_config>
        <localfile>
          <log_format>audit</log_format>
          <location>/var/log/audit/audit.log</location>
        </localfile> 

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/output.log</location>
        </localfile>

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/input.log</location>
        </localfile>
      </ossec_config>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  when: not grep_ossec_conf.rc == 0
  notify: "start/enable wazuh-agent"

- name: Edit ossec conf file without audit
  ansible.builtin.blockinfile:
    path: "/var/ossec/etc/ossec.conf"
    block: |
      <ossec_config>
        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/output.log</location>
        </localfile>

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/input.log</location>
        </localfile>
      </ossec_config>
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
  when: grep_ossec_conf.rc == 0
  notify: "start/enable wazuh-agent"
