---
# handlers for freebsd_pf

- name: enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  when:
    - pf_fail2ban_enable|bool
    - pf_fail2ban_service.stat.exists

- name: disable and stop fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: stopped
    enabled: false
  when:
    - not pf_fail2ban_enable|bool
    - pf_fail2ban_service.stat.exists

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when:
    - pf_fail2ban_enable|bool
    - pf_fail2ban_service.stat.exists

- name: reload fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: reloaded
  when:
    - pf_fail2ban_enable|bool
    - pf_fail2ban_service.stat.exists

# EOF
...
