files_to_backup:
  - "/etc/shadow"
  - "/etc/passwd"
  - "/etc/gshadow"
  - "/etc/group"
files_to_fix_permissions:
  - "/etc/passwd"
  - "/etc/shadow"
  - "/etc/gshadow"
  - "/etc/group"
  - "/usr/bin/pkexec"

#Might have to enumerate cuz of packages changes
packages_to_install:
  - "auditd"
  - "rsyslog"
packages_to_remove:
  - "nc"
php_settings:
  disable_functions: "shell_exec, exec, passthru, proc_open, popen, system, phpinfo, expect_popen"
  max_execution_time: "3"
  register_globals: "off"
  magic_quotes_gpc: "on"
  allow_url_fopen: "off"
  allow_url_include: "off"
  display_errors: "off"
  short_open_tag: "off"
  session.cookie_httponly: "1"
  session.use_only_cookies: "1"
  session.cookie_secure: "1"
sysctl_settings:
  net.ipv4.tcp_syncookies: "1"
  net.ipv4.tcp_synack_retries: "2"
  net.ipv4.tcp_challenge_ack_limit: "1000000"
  net.ipv4.tcp_rfc1337: "1"
  net.ipv4.icmp_ignore_bogus_error_responses: "1"
  net.ipv4.conf.all.accept_redirects: "0"
  net.ipv4.icmp_echo_ignore_all: "1"
  kernel.core_uses_pid: "1"
  kernel.kptr_restrict: "2"
  kernel.perf_event_paranoid: "2"
  kernel.randomize_va_space: "2"
  kernel.sysrq: "0"
  kernel.yama.ptrace_scope: "2"
  fs.protected_hardlinks: "1"
  fs.protected_symlinks: "1"
  fs.suid_dumpable: "0"
  kernel.unprivileged_userns_clone: "0"
  fs.protected_fifos: "2"
  fs.protected_regular: "2"
  kernel.kptr_restrict: "2"