---
- name: Install on Solaris 10
  when: ansible_distribution_major_version | int == 10
  community.general.svr4pkg:
    name: "wazuh-agent"
    src: "https://packages.wazuh.com/4.x/solaris/i386/10/wazuh-agent_v4.7.2-sol10-i386.pkg"
    state: "present"

- name: Install on Solaris 11
  when: ansible_distribution_major_version | int == 11
  block:
    - name: Download p5p file
      ansible.builtin.get_url:
        url: "https://packages.wazuh.com/4.x/solaris/i386/11/wazuh-agent_v4.7.2-sol11-i386.p5p"
        dest: "/tmp/"
    
    - name: Install wazuh agent
      ansible.builtin.shell: "pkg install -g /tmp/wazuh-agent_v4.7.2-sol11-i386.p5p wazuh-agent"

- name: Add manager IP
  ansible.builtin.replace:
    path: "/var/ossec/etc/ossec.conf"
    regexp: "MANAGER_IP"
    replace: "{{ manager_ip }}"

- name: add hostname
  ansible.builtin.blockinfile:
    path: "/var/ossec/etc/ossec.conf"
    insertafter: "<client>"
    block: |
        <enrollment>
          <agent_name>{{ inventory_hostname }}</agent_name>
        <enrollment>

- name: Start wazuh agent
  ansible.builtin.shell: "/var/ossec/bin/wazuh-control start"
