---
- name: use iptables to let domain ports in tcp
  ansible.builtin.iptables:
    action: "append"
    chain: "INPUT"
    source_port: "{{ port }}"
    source: "{{ ip }}"
    jump: "ACCEPT"
    protocol: "tcp"
    state: "present"
  loop: "{{ linux_dc_ports_tcp }}"
  loop_control:
    loop_var: port

- name: use iptables to let domain ports in udp
  ansible.builtin.iptables:
    action: "append"
    chain: "INPUT"
    source_port: "{{ port }}"
    source: "{{ ip }}"
    jump: "ACCEPT"
    protocol: "udp"
    state: "present"
  loop: "{{ dc_ports_udp }}"
  loop_control:
    loop_var: port

- name: use iptables to let domain ports out tcp
  ansible.builtin.iptables:
    action: "append"
    chain: "OUTPUT"
    destination_port: "{{ port }}"
    destination: "{{ ip }}"
    jump: "ACCEPT"
    protocol: "tcp"
    state: "present"
  loop: "{{ linux_dc_ports_tcp }}"
  loop_control:
    loop_var: port

- name: use iptables to let domain ports out udp
  ansible.builtin.iptables:
    action: "append"
    chain: "OUTPUT"
    destination_port: "{{ port }}"
    destination: "{{ ip }}"
    jump: "ACCEPT"
    protocol: "udp"
    state: "present"
  loop: "{{ dc_ports_udp }}"
  loop_control:
    loop_var: port
