- name: Allow DC to and from linux
  when: ansible_system | lower == "linux"
  include_tasks: linux.yaml
  loop: "{{ dc_ips }}"
  loop_control:
    loop_var: ip

- name: Allow DC to and from windows
  when: ansible_os_family | lower == "windows"
  include_tasks: windows.yaml
