# Install Rust on a Linux system

- name: Installing Rust
  become: no
  ansible.builtin.shell:
    cmd: "{{ rust_cmd }}"

- name: Running Rustup update
  become: no
  ansible.builtin.command:
    cmd: rustup update

- name: Copying Rust Files
  ansible.builtin.copy:
    src: "{{ cargo_bin_path }}"
    remote_src: true
    dest: /bin/

- name: Copying Cargo Files
  ansible.builtin.copy:
    src: "{{ cargo_path }}"
    remote_src: true
    dest: /root/

- name: Initializing Rust versions
  ansible.builtin.command:
    cmd: /bin/rustup default stable
