!     GENERATES A HUMAN READABLE PASSWORD. WORKS ON POSIX SYSTEMS ONLY
!      
!     THIS PROGRAM WOULD HAVE WASTED SO MANY PUNCH CARDS WITH ITS
!     FORMATTING, BUT I HAD TO FOLLOW SEMI-MODERN PROGRAMMING
!     PRACTICES SOMEHOW. SORRY, ENVIRONMENT

      PROGRAM GENPASSWD
      IMPLICIT NONE
      INTEGER I
      INTEGER CURRENTCHARNO
      INTEGER CURRENTWORDNO
      INTEGER IOERROR
      CHARACTER, ALLOCATABLE :: WORDS (:, :)
      CHARACTER CURRBYTE
      INTEGER CURRBYTENO
      INTEGER, ALLOCATABLE :: RANDOMCHOICE (:)
      REAL RANDOMNUMBER
      CHARACTER (19) :: WRITEBUFFER

      ALLOCATE(WORDS(16384, 19))
      ALLOCATE(RANDOMCHOICE(4))

      OPEN(8, ACCESS="DIRECT", ACTION="READ", FILE="WORDLIST.TXT",      &
     &FORM="UNFORMATTED", IOSTAT=IOERROR, RECL=1)

!     THE CHARACTER WE ARE CURRENTLY ON WITHIN THE WORD
      CURRENTCHARNO = 1
!     THE WORD WE ARE CURRENTLY ON
      CURRENTWORDNO = 1
      CURRBYTENO = 1
      DO
      READ(8, REC=CURRBYTENO, ERR=102) CURRBYTE

      IF (CURRBYTE .EQ. TRANSFER(10, CURRBYTE)) THEN
        CURRENTCHARNO = 1
        CURRENTWORDNO = CURRENTWORDNO + 1
      ELSE
        WORDS(CURRENTWORDNO, CURRENTCHARNO) = CURRBYTE
        CURRENTCHARNO = CURRENTCHARNO + 1
      END IF

      CURRBYTENO = CURRBYTENO + 1
      END DO

  102 DO I=1,4
      CALL RANDOM_NUMBER(HARVEST=RANDOMNUMBER)
      RANDOMCHOICE(I) = 1 + RANDOMNUMBER * 16383
      END DO
      
      DO I=1,4
      WRITEBUFFER = TRANSFER(WORDS(RANDOMCHOICE(I), 1:19), WRITEBUFFER)
      WRITE(6, FMT="(A)", ADVANCE="NO") WRITEBUFFER
      WRITE(6, FMT="(A)", ADVANCE="NO") " "
      END DO

      END PROGRAM GENPASSWD

