# Removes Users

- name: Remove Local Users on Windows
  ansible.windows.win_user:
    name: "{{ item }}"
    state: absent
  loop: "{{ users }}"
  when: ansible_os_family | lower == "windows"

- name: Remove Local Users on Linux
  become: yes
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
  loop: "{{ users }}"
  when: ansible_system | lower == "linux"
