- name: uninstall for all linux operating systems
  ansible.builtin.package:
    state: "absent"
    name: "wazuh-agent"

- name: disable wazuh agent
  ansible.builtin.service:
    enabled: false
    state: "stopped"
    name: "wazuh-agent"

