windows:
  hosts:
    Windows2016:
      ansible_host: 10.0.0.16
      ansible_user: Administrator
      ansible_password: Is1WaterWet?
      ansible_connection: winrm
      ansible_winrm_scheme: http
      ansible_port: 5985
      ansible_winrm_transport: ntlm
      domain_controller: true
      in_domain: true
      required_ports:
      - 22
      - 53
linux:
  hosts:
    Debian:
      ansible_host: 10.0.0.11
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: true
      required_ports:
      - 22
    Centos:
      ansible_host: 10.0.0.12
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: false
      required_ports:
      - 20
      - 21
      - 22
bsd:
  hosts:
    FreeBased:
      ansible_host: 10.0.0.13
      ansible_user: root
      ansible_password: Is1WaterWet?
      ansible_connection: ssh
      in_domain: true
manager:
  hosts:
    Centos:
      ansible_host: 10.0.0.12
      ansible_user: root
      ansible_password: Is1WaterWet?
      in_domain: false
      required_ports:
      - 20
      - 21
      - 22
