- name: Fail task for compatability
  ansible.builtin.command: /bin/false
  
#- name: Install on Leap and SLES
#  community.general.zypper_repository:
#    repo: https://download.opensuse.org/repositories/server:monitoring/openSUSE_Leap_15.3/server:monitoring.repo
#    state: present
#  when: ansible_distribution == "SLES" or ( ansible_distribution | lower == "opensuse leap" and ansible_distribution_version == "15.3")
#
#- name: Install on Tumbleweed
#  community.general.zypper_repository:
#    repo: https://download.opensuse.org/repositories/server:monitoring/openSUSE_Tumbleweed/server:monitoring.repo
#    state: present
#  when: ansible_distribution | lower == "opensuse tumbleweed"
#
#- name: Install on Factory zSystems
#  community.general.zypper_repository:
#    repo: https://download.opensuse.org/repositories/server:monitoring/openSUSE_Factory_zSystems/server:monitoring.repo
#    state: present
#  when: ansible_distribution | lower == "opensuse factory zsystems"
#
#- name: Install on Factory PowerPC
#  community.general.zypper_repository:
#    repo: https://download.opensuse.org/repositories/server:monitoring/openSUSE_Factory_PowerPC_standard/server:monitoring.repo
#    state: present
#  when: ansible_distribution | lower == "opensuse factory powerpc"
#
#- name: Install on Factory Arm
#  community.general.zypper_repository:
#    repo: https://download.opensuse.org/repositories/server:monitoring/openSUSE_Factory_ARM/server:monitoring.repo 
#    state: present
#  when: ansible_distribution | lower == "opensuse factory arm"
#
#- name: Install on Suse15.4
#  community.general.zypper_repository:
#    repo: https://download.opensuse.org/repositories/server:monitoring/15.4/server:monitoring.repo 
#    state: present
#  when: ansible_distribution | lower == "opensuse" and ansible_distribution_version == "15.4"
#
#- name: Install on Suse15.5
#  community.general.zypper_repository:
#    repo: https://download.opensuse.org/repositories/server:monitoring/15.5/server:monitoring.repo 
#    state: present
#  when: ansible_distribution | lower == "opensuse" and ansible_distribution_version == "15.5"
#
#- name: Refresh and update all packages on Suse
#  community.general.zypper:
#    name: '*'
#    update_cache: true
#    state: latest
#
#- name: Install on All Suse to Catch Repo Errors
#  community.general.zypper:
#    name: suricata
#    state: present
#    update_cache: true
