# Tasks to Configure and Start Suricata on Linux

- name: Gathering package facts
  ansible.builtin.package_facts:
    manager: auto
    strategy: first

- name: Check Suricata Package Version
  ansible.builtin.set_fact:
    suricata_ver_index: "{{ ansible_facts.packages['suricata'][0]['version'].index('.') | int - 1 }}"
  when: '"suricata" in ansible_facts.packages'

- name: Configuring suricata.yaml for suricata v7
  template:
    src: linux-suricata7.j2
    dest: "{{ config_path }}"
  notify: "restart suricata"
  when: "'suricata' in ansible_facts.packages and ansible_facts.packages['suricata'][0]['version'][suricata_ver_index | int] == '7'"
 
- name: Configuring suricata.yaml for suricata v6
  template:
    src: linux-suricata6.j2
    dest: "{{ config_path }}"
  notify: "restart suricata"
  when: "'suricata' in ansible_facts.packages and ansible_facts.packages['suricata'][0]['version'][suricata_ver_index | int] == '6'"

- name: Configuring suricata for source install
  template:
    src: linux-suricata6.j2
    dest: "{{ config_path }}"
  notify: "restart suricata"
  when: "not 'suricata' in ansible_facts.packages"
