version: '3'
services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    environment:
      NTFY_BASE_URL: http://ntfy.example.com
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
      NTFY_WEB_PUSH_PUBLIC_KEY: BG--Eu9agTnbr96bb5ExlH4MThQGY8lEK6kdFRhBdcSJUo7ErXzw46oEOk_L-k99ExVbtOeyfMFqy8qlsDx8-GI
      NTFY_WEB_PUSH_PRIVATE_KEY: eViNOkSWieyQfPFOIr8ZmOEoJCpPbQp386MzyJQ1ei0
      NTFY_WEB_PUSH_FILE: /var/lib/ntfy/webpush.db
      NTFY_WEB_PUSH_EMAIL_ADDRESS: admin@example.invalid
    volumes:
      - ./:/var/lib/ntfy
    ports:
      - 20402:80
    command: serve
