# Install Suricata on Windows

- name: Install Suricata on Windows
  hosts: windows
  become: yes
  become_method: runas
  become_user: Administrator
  vars_files:
    - group_vars/all.yaml
  tags:
    - install
    - Windows
  roles:
    - windows

# Install Suricata on Linux Distros
- name: Install Suricata on Linux
  hosts: linux
  become: yes
  vars_files:
    - group_vars/all.yaml
  tags:
    - install
    - Linux
  roles:
    - linux_setup
    - role: linux_configure
      tags: Configuration
