# Tasks to create users on hosts

- name: Create Local Users on Windows
  ansible.windows.win_user:
    name: "{{ item.0 }}"
    password: "{{ item.1 }}"
    state: present
  with_together:
    - "{{ users | list }}"
    - "{{ passwords | list }}"
  when: ansible_os_family | lower == "windows"

- name: Create Local Users on Linux
  become: yes
  ansible.builtin.user:
    name: "{{ item.0 }}"
    password: "{{ item.1 | password_hash('sha256') }}"
    state: present
  with_together:
    - "{{ users | list }}"
    - "{{ passwords | list }}"
  when: ansible_system | lower == "linux"
